// Per-look description — a short, UNIQUE blurb generated by Gemini from the
// look's poster frame + the products featured in it. Cached server-side in
// look_descriptions; this module reads that cache directly (public-readable, so
// it works for logged-out viewers) and falls back to the `look-description`
// edge function to generate one on demand for signed-in viewers.
//
// This replaces the old behaviour where every look fell back to a single
// creator-level "about" blurb, so unrelated looks under one creator read
// identically (and named brands that weren't even in the look).

import { supabase } from '~/utils/supabase';

export interface LookDescriptionProduct {
  brand?: string | null;
  name?: string | null;
  type?: string | null;
  price?: string | null;
}

export interface LookDescriptionInput {
  /** The look's DB uuid (looks.id). Required — keys the cache. */
  lookId: string;
  title?: string | null;
  /** Poster frame URL Gemini analyses (the still the feed already paints). */
  imageUrl?: string | null;
  products: LookDescriptionProduct[];
}

/** Read a cached description without triggering generation. Returns null when
 *  none exists yet (or Supabase isn't configured / lookId missing). */
export async function getCachedLookDescription(lookId: string): Promise<string | null> {
  if (!supabase || !lookId) return null;
  const { data } = await supabase
    .from('look_descriptions')
    .select('description')
    .eq('look_id', lookId)
    .maybeSingle();
  return (data?.description as string | undefined) || null;
}

/** Generate (and cache) a description via the edge function. Generation is
 *  auth-gated, so this no-ops for logged-out viewers. */
export async function generateLookDescription(input: LookDescriptionInput): Promise<string | null> {
  if (!supabase || !input.lookId) return null;
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) return null;
  const { data, error } = await supabase.functions.invoke('look-description', {
    body: {
      lookId: input.lookId,
      title: input.title ?? '',
      imageUrl: input.imageUrl ?? '',
      products: input.products ?? [],
    },
  });
  if (error) return null;
  return (data?.description as string | undefined) || null;
}

/** Cache-first resolve: return the cached blurb if present, otherwise try to
 *  generate one (signed-in only). */
export async function getLookDescription(input: LookDescriptionInput): Promise<string | null> {
  const cached = await getCachedLookDescription(input.lookId);
  if (cached) return cached;
  return generateLookDescription(input);
}
