import { useEffect, useState } from 'react';
import { supabase } from '~/utils/supabase';

/**
 * Lookup a brand's logo URL with a three-tier fallback chain:
 *   1. public.brand_logos row (admin-curated, always wins)
 *   2. Brandfetch Logo CDN by domain — derived from any product
 *      under this brand whose URL has a parseable hostname
 *   3. null (caller falls back to text label)
 *
 * Results are memoised module-level so 100 tiles for the same brand
 * share a single fetch + single Brandfetch URL build.
 */

// Public client id — safe to bundle. Generated by registering the
// app on brandfetch.com. Used by their Logo CDN to authorise
// referrers, not a secret.
const BRANDFETCH_CLIENT_ID = '1id3n10pdBTarCHI0db';

function brandfetchUrl(domain: string): string {
  return `https://cdn.brandfetch.io/${domain}?c=${BRANDFETCH_CLIENT_ID}`;
}

function domainFromUrl(raw: string | null | undefined): string | null {
  if (!raw) return null;
  try {
    const u = new URL(raw);
    // Strip leading www. — Brandfetch's canonical domain is the
    // bare host (apple.com, not www.apple.com).
    return u.hostname.replace(/^www\./i, '');
  } catch {
    return null;
  }
}

interface CacheEntry { url: string | null; loading: boolean }
const cache = new Map<string, CacheEntry>();
const subscribers = new Map<string, Set<(url: string | null) => void>>();

function notify(key: string, url: string | null) {
  const set = subscribers.get(key);
  if (!set) return;
  for (const cb of set) cb(url);
}

async function fetchLogo(key: string): Promise<void> {
  if (!supabase) { cache.set(key, { url: null, loading: false }); notify(key, null); return; }
  // Tier 1: admin-curated row in brand_logos.
  const { data: curated } = await supabase
    .from('brand_logos')
    .select('logo_url')
    .eq('brand', key)
    .maybeSingle();
  if (curated?.logo_url) {
    cache.set(key, { url: curated.logo_url as string, loading: false });
    notify(key, curated.logo_url as string);
    return;
  }
  // Tier 2: Brandfetch CDN via a domain we can derive from any
  // product under this brand. Single product query — cheap, results
  // memoised so subsequent renders skip it.
  const { data: products } = await supabase
    .from('products')
    .select('url')
    .ilike('brand', key)
    .not('url', 'is', null)
    .limit(5);
  for (const row of (products || []) as { url: string | null }[]) {
    const domain = domainFromUrl(row.url);
    if (domain) {
      const url = brandfetchUrl(domain);
      cache.set(key, { url, loading: false });
      notify(key, url);
      return;
    }
  }
  // Tier 3: no logo — caller falls back to text.
  cache.set(key, { url: null, loading: false });
  notify(key, null);
}

export function useBrandLogo(brand: string | null | undefined): string | null {
  const key = (brand || '').toLowerCase().trim();
  const [url, setUrl] = useState<string | null>(() => cache.get(key)?.url ?? null);

  useEffect(() => {
    if (!key) { setUrl(null); return; }
    const existing = cache.get(key);
    if (existing && !existing.loading) {
      setUrl(existing.url);
      return;
    }
    const set = subscribers.get(key) ?? new Set();
    set.add(setUrl);
    subscribers.set(key, set);
    if (!existing) {
      cache.set(key, { url: null, loading: true });
      void fetchLogo(key);
    }
    return () => { set.delete(setUrl); };
  }, [key]);

  return url;
}
