import { useEffect, useState } from 'react';
import { supabase } from '~/utils/supabase';

/**
 * Lookup a brand's logo URL with a three-tier fallback chain:
 *   1. public.brand_logos row (admin-curated, always wins)
 *   2. Brandfetch Logo CDN by domain — derived from any product
 *      under this brand whose URL has a parseable hostname
 *   3. null (caller falls back to text label)
 *
 * Results are memoised module-level so 100 tiles for the same brand
 * share a single fetch + single Brandfetch URL build.
 */

// Public client id — safe to bundle. Generated by registering the
// app on brandfetch.com. Used by their Logo CDN to authorise
// referrers, not a secret.
const BRANDFETCH_CLIENT_ID = '1id3n10pdBTarCHI0db';

function brandfetchUrl(domain: string): string {
  return `https://cdn.brandfetch.io/${domain}?c=${BRANDFETCH_CLIENT_ID}`;
}

function domainFromUrl(raw: string | null | undefined): string | null {
  if (!raw) return null;
  try {
    const u = new URL(raw);
    // Strip leading www. — Brandfetch's canonical domain is the
    // bare host (apple.com, not www.apple.com).
    return u.hostname.replace(/^www\./i, '');
  } catch {
    return null;
  }
}

interface CacheEntry { url: string | null; loading: boolean }
const cache = new Map<string, CacheEntry>();
const subscribers = new Map<string, Set<(url: string | null) => void>>();

function notify(key: string, url: string | null) {
  const set = subscribers.get(key);
  if (!set) return;
  for (const cb of set) cb(url);
}

async function fetchLogo(key: string): Promise<void> {
  if (!supabase) { cache.set(key, { url: null, loading: false }); notify(key, null); return; }
  // Tier 1: admin-curated row in brand_logos.
  const { data: curated } = await supabase
    .from('brand_logos')
    .select('logo_url')
    .eq('brand', key)
    .maybeSingle();
  if (curated?.logo_url) {
    cache.set(key, { url: curated.logo_url as string, loading: false });
    notify(key, curated.logo_url as string);
    return;
  }
  // Tier 2: Brandfetch CDN via a domain we can derive from any
  // product under this brand. Single product query — cheap, results
  // memoised so subsequent renders skip it.
  const { data: products } = await supabase
    .from('products')
    .select('url')
    .ilike('brand', key)
    .not('url', 'is', null)
    .limit(5);
  for (const row of (products || []) as { url: string | null }[]) {
    const domain = domainFromUrl(row.url);
    if (domain) {
      const url = brandfetchUrl(domain);
      cache.set(key, { url, loading: false });
      notify(key, url);
      return;
    }
  }
  // Tier 3: no logo — caller falls back to text.
  cache.set(key, { url: null, loading: false });
  notify(key, null);
}

/**
 * Batch-warm the logo cache for many brands in ONE query instead of the
 * per-brand tier-1 lookup fetchLogo() fires. Curated rows come from a single
 * `.in('brand', …)` on brand_logos; brands without a curated row fall back to
 * a Brandfetch URL derived from the product URLs already in memory (no extra
 * query). Call once after the home feed loads.
 *
 * Brands with neither a curated row nor a derivable in-memory domain settle to
 * the text fallback (url=null) — the same tier-3 result the lazy path reaches.
 * In-memory products are exactly the feed's cards, so domain coverage is high.
 */
export async function prefetchBrandLogos(
  products: ReadonlyArray<{ brand?: string | null; url?: string | null }>,
): Promise<void> {
  if (!supabase) return;
  const domainByBrand = new Map<string, string>();
  const brands = new Set<string>();
  for (const p of products) {
    const key = (p.brand || '').toLowerCase().trim();
    if (!key) continue;
    brands.add(key);
    if (!domainByBrand.has(key)) {
      const domain = domainFromUrl(p.url);
      if (domain && !domain.includes('google.com') && !domain.endsWith('amazon.com')) {
        domainByBrand.set(key, domain);
      }
    }
  }
  // Skip brands already resolved (a non-loading cache entry).
  const todo = [...brands].filter(b => { const e = cache.get(b); return !e || e.loading; });
  if (todo.length === 0) return;
  // Reserve them so concurrent useBrandLogo() mounts await our notify() rather
  // than each firing their own per-brand tier-1 query.
  for (const b of todo) cache.set(b, { url: null, loading: true });
  // Tier 1 — a single query for every curated row.
  const curated = new Map<string, string>();
  const { data } = await supabase
    .from('brand_logos').select('brand, logo_url').in('brand', todo);
  for (const row of (data || []) as { brand: string; logo_url: string | null }[]) {
    const k = (row.brand || '').toLowerCase().trim();
    if (k && row.logo_url) curated.set(k, row.logo_url);
  }
  // Resolve: curated row > Brandfetch-by-domain > text fallback (null).
  for (const b of todo) {
    const url = curated.get(b)
      ?? (domainByBrand.has(b) ? brandfetchUrl(domainByBrand.get(b)!) : null);
    cache.set(b, { url, loading: false });
    notify(b, url);
  }
}

export function useBrandLogo(brand: string | null | undefined): string | null {
  const key = (brand || '').toLowerCase().trim();
  const [url, setUrl] = useState<string | null>(() => cache.get(key)?.url ?? null);

  useEffect(() => {
    if (!key) { setUrl(null); return; }
    const existing = cache.get(key);
    if (existing && !existing.loading) {
      setUrl(existing.url);
      return;
    }
    const set = subscribers.get(key) ?? new Set();
    set.add(setUrl);
    subscribers.set(key, set);
    if (!existing) {
      cache.set(key, { url: null, loading: true });
      void fetchLogo(key);
    }
    return () => { set.delete(setUrl); };
  }, [key]);

  return url;
}
