-- 015: Product ads table for AI-generated ad videos
-- Stores ad creatives generated from selected products via Veo + Claude

CREATE TABLE IF NOT EXISTS product_ads (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id       uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  title            text,                                    -- ad headline / title
  description      text,                                    -- ad copy generated by Claude
  video_url        text,                                    -- Supabase storage public URL
  storage_path     text,                                    -- Supabase storage path
  thumbnail_url    text,                                    -- poster frame
  affiliate_url    text,                                    -- product affiliate/tracking link
  prompt           text,                                    -- Veo prompt used
  style            text NOT NULL DEFAULT 'studio_clean',    -- video style used
  veo_model        text DEFAULT 'veo-3.1-fast-generate-preview',
  status           text NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending','generating','done','failed','live','paused')),
  duration_seconds numeric DEFAULT 4,
  aspect_ratio     text DEFAULT '9:16',
  resolution       text DEFAULT '720p',
  cost_usd         numeric,
  impressions      integer DEFAULT 0,
  clicks           integer DEFAULT 0,
  error            text,
  enabled          boolean DEFAULT false,                   -- whether to show in feed
  created_at       timestamptz DEFAULT now(),
  completed_at     timestamptz,
  updated_at       timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_ads_product ON product_ads(product_id);
CREATE INDEX IF NOT EXISTS idx_product_ads_status ON product_ads(status);
CREATE INDEX IF NOT EXISTS idx_product_ads_enabled ON product_ads(enabled) WHERE enabled = true;

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE product_ads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read product_ads" ON product_ads FOR SELECT USING (true);

-- Service role write access
CREATE POLICY "Service write product_ads" ON product_ads
  FOR ALL USING (auth.role() = 'service_role');

-- Authenticated users can insert/update (admin panel)
CREATE POLICY "Authenticated write product_ads" ON product_ads
  FOR ALL USING (auth.role() = 'authenticated');

-- ============================================
-- UPDATED_AT TRIGGER
-- ============================================

CREATE TRIGGER set_product_ads_updated_at
  BEFORE UPDATE ON product_ads
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ============================================
-- RPC FUNCTIONS FOR ATOMIC COUNTER INCREMENTS
-- ============================================

CREATE OR REPLACE FUNCTION increment_ad_impressions(ad_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE product_ads SET impressions = impressions + 1 WHERE id = ad_id;
END;
$$;

CREATE OR REPLACE FUNCTION increment_ad_clicks(ad_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE product_ads SET clicks = clicks + 1 WHERE id = ad_id;
END;
$$;
