-- 060: Auto-embed creatives on insert / completion.
--
-- Until now embeddings were generated by:
--   • the admin panel calling triggerEmbedEntity() after editing a creative
--   • the nightly search-backfill cron sweeping cold misses
--
-- Both leave a window where a freshly rendered creative is searchable by
-- BM25 (concept_doc indexed) but invisible to the dense lane until something
-- backfills it. Mirror the existing 046_product_creative_webhook pattern: an
-- AFTER INSERT OR UPDATE trigger that POSTs to the embed-entity edge function
-- whenever a live creative has no text_embedding yet.
--
-- Why product_creative only:
--   The consumer feed indexes product_creative directly (see migration 058).
--   products.text_embedding and looks.text_embedding columns exist (057) but
--   no production search path queries them — adding triggers there now would
--   fire embeddings nothing reads. If/when search_products_hybrid or
--   search_looks_hybrid is wired back into nl-search, add equivalent triggers
--   in a follow-up migration.

-- ── 1. Vault secret for service-role JWT ────────────────────────────────────
-- embed-entity accepts the anon key (it doesn't gate on auth) but using the
-- service role keeps the call symmetric with search-backfill. Idempotent.
do $$
declare
  v_id uuid;
begin
  select id into v_id from vault.secrets where name = 'embed_entity_service_key';
  if v_id is null then
    perform vault.create_secret(
      'PLACEHOLDER_REPLACE_VIA_DASHBOARD',
      'embed_entity_service_key',
      'Service-role JWT for trigger-fired embed-entity calls (migration 060).'
    );
  end if;
end $$;

-- ── 2. Trigger function ─────────────────────────────────────────────────────
create or replace function notify_embed_creative()
returns trigger
language plpgsql
security definer
as $$
declare
  v_token text;
begin
  -- Only fire when the creative is live, has a renderable video, and is not
  -- yet embedded. Updating any other column (e.g. impressions, clicks,
  -- enabled flag) must NOT re-trigger embedding.
  if NEW.status = 'live'
     and NEW.video_url is not null
     and NEW.text_embedding is null
  then
    select decrypted_secret into v_token
      from vault.decrypted_secrets
     where name = 'embed_entity_service_key'
     limit 1;

    -- Skip silently if the secret hasn't been populated yet (migration runs
    -- before the dashboard rotation). The nightly backfill will catch the row.
    if v_token is null or v_token = 'PLACEHOLDER_REPLACE_VIA_DASHBOARD' then
      return NEW;
    end if;

    perform net.http_post(
      url     := 'https://vtarjrnqvcqbhoclvcur.supabase.co/functions/v1/embed-entity',
      headers := jsonb_build_object(
        'Content-Type',  'application/json',
        'Authorization', 'Bearer ' || v_token
      ),
      body    := jsonb_build_object(
        'id',          NEW.id,
        'entity_type', 'creative',
        'force',       false
      )
    );
  end if;
  return NEW;
end;
$$;

comment on function notify_embed_creative() is
  'Fires embed-entity for any product_creative row that is live + has a video + has no text_embedding yet. Wired by trg_product_creative_auto_embed.';

-- ── 3. Trigger ──────────────────────────────────────────────────────────────
-- AFTER INSERT covers fresh rows (e.g. backfill imports that ship as live).
-- AFTER UPDATE OF status, video_url covers the common path where a row starts
-- as 'pending', the Modal worker writes video_url + flips status to 'live',
-- and we want to embed at that point.
drop trigger if exists trg_product_creative_auto_embed on product_creative;

create trigger trg_product_creative_auto_embed
  after insert or update of status, video_url
  on product_creative
  for each row
  execute function notify_embed_creative();
