-- 069 — Search v2: looks lane + shopper-language facet_text
--
-- Three changes that together fix the "date night / summer outfit / candles /
-- best for summer / black jeans combination" failure modes called out by the
-- user, *without* re-polluting concept_doc with shopper phrases:
--
--   1. facet_text column on products, looks, product_creative — short
--      comma-joined list of plausible occasions, seasons, vibes generated by
--      Haiku in embed-entity. Indexed with BM25 weight C (informational only;
--      can't dominate name/brand). Lets queries like "date night" actually
--      hit something in the index.
--
--   2. search_looks_hybrid RPC — dense + BM25 + RRF over looks
--      (looks ⨝ look_products) so vibe / occasion / outfit queries can route
--      to the looks lane first. Looks already have text_embedding +
--      concept_doc populated for 18/18 live rows; we just couldn't search
--      them. RPC mirrors the search_*_hybrid shape so nl-search can merge
--      results with one normaliser.
--
--   3. Update search_creatives_hybrid + search_products_hybrid BM25 lanes to
--      include facet_text at weight C. Keeps existing weighting intact.
--
-- Safe to apply in one shot. New columns default NULL — existing rows keep
-- working. Embed-entity will populate facet_text on next embed cycle (force
-- repopulate via scripts/reembed.mjs after deploy).

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. facet_text columns
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.products
  add column if not exists facet_text text;
comment on column public.products.facet_text is
  'Shopper-language facet phrases (occasions, seasons, vibes) generated by embed-entity. Indexed at BM25 weight C — does NOT pollute factual concept_doc but lets queries like "date night" hit the index.';

alter table public.looks
  add column if not exists facet_text text;
comment on column public.looks.facet_text is
  'Shopper-language facet phrases for looks (occasions, seasons, vibes). Same role as products.facet_text.';

alter table public.product_creative
  add column if not exists facet_text text;
comment on column public.product_creative.facet_text is
  'Shopper-language facet phrases for creatives. Same role as products.facet_text.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. search_looks_hybrid RPC
-- ─────────────────────────────────────────────────────────────────────────────
-- Output shape mirrors search_creatives_hybrid where possible so nl-search
-- can normalise both lanes through the same code path. The "video_url" and
-- "thumbnail_url" come from the look's first associated creative if any
-- exists, else null — the client renders a look-card with the look thumbnail.

drop function if exists public.search_looks_hybrid(vector, text, int, text, uuid[], int);

create or replace function public.search_looks_hybrid(
  query_embedding vector(1536),
  query_text      text,
  k               int     default 24,
  filter_gender   text    default null,
  exclude_ids     uuid[]  default '{}'::uuid[],
  min_results     int     default 8
)
returns table(
  id                uuid,
  look_id           uuid,
  look_title        text,
  look_creator      text,
  look_description  text,
  look_gender       text,
  look_color        text,
  concept_doc       text,
  concept_facets    jsonb,
  facet_text        text,
  rrf_score         double precision,
  dense_rank        bigint,
  bm25_rank         bigint
)
language sql
stable
as $$
  with candidates as (
    select l.id
    from public.looks l
    where l.status = 'live'
      and l.enabled = true
      and (filter_gender is null or l.gender is null or l.gender = filter_gender or l.gender = 'unisex')
      and (exclude_ids is null or array_length(exclude_ids, 1) is null or l.id <> all(exclude_ids))
  ),
  dense as (
    select
      c.id,
      row_number() over (order by l.text_embedding <=> query_embedding) as rk
    from candidates c
    join public.looks l on l.id = c.id
    where l.text_embedding is not null
    order by l.text_embedding <=> query_embedding
    limit k * 4
  ),
  bm25 as (
    select
      c.id,
      row_number() over (
        order by ts_rank_cd(
          setweight(to_tsvector('english', coalesce(l.title,         '')), 'A') ||
          setweight(to_tsvector('english', coalesce(l.creator_handle,'')), 'B') ||
          setweight(to_tsvector('english', coalesce(l.description,   '')), 'B') ||
          setweight(to_tsvector('english', coalesce(l.concept_doc,   '')), 'B') ||
          setweight(to_tsvector('english', coalesce(l.facet_text,    '')), 'C'),
          websearch_to_tsquery('english', query_text)
        ) desc
      ) as rk
    from candidates c
    join public.looks l on l.id = c.id
    where coalesce(btrim(query_text), '') <> ''
      and (
        setweight(to_tsvector('english', coalesce(l.title,         '')), 'A') ||
        setweight(to_tsvector('english', coalesce(l.creator_handle,'')), 'B') ||
        setweight(to_tsvector('english', coalesce(l.description,   '')), 'B') ||
        setweight(to_tsvector('english', coalesce(l.concept_doc,   '')), 'B') ||
        setweight(to_tsvector('english', coalesce(l.facet_text,    '')), 'C')
      ) @@ websearch_to_tsquery('english', query_text)
    limit k * 4
  ),
  fused as (
    select
      coalesce(d.id, b.id) as id,
      (coalesce(1.0 / (60.0 + d.rk), 0.0) +
       coalesce(1.0 / (60.0 + b.rk), 0.0))::double precision as rrf_score,
      d.rk as dense_rank,
      b.rk as bm25_rank
    from dense d
    full outer join bm25 b on d.id = b.id
    order by rrf_score desc
    limit k
  )
  select
    l.id,
    l.id              as look_id,
    l.title           as look_title,
    l.creator_handle  as look_creator,
    l.description     as look_description,
    l.gender          as look_gender,
    l.color           as look_color,
    l.concept_doc,
    l.concept_facets,
    l.facet_text,
    f.rrf_score,
    f.dense_rank,
    f.bm25_rank
  from fused f
  join public.looks l on l.id = f.id
  order by f.rrf_score desc;
$$;

comment on function public.search_looks_hybrid(vector(1536), text, int, text, uuid[], int) is
  'Hybrid dense+BM25 RRF retrieval over looks. Routed first by nl-search for vibe/occasion/outfit intents.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Update search_creatives_hybrid + search_products_hybrid BM25 to include
--    facet_text at weight C.
-- ─────────────────────────────────────────────────────────────────────────────
-- Re-create both functions verbatim from 067 with facet_text added to the
-- BM25 tsvector. Weights for existing fields are unchanged.

drop function if exists public.search_products_hybrid(vector, text, int, text, text[], uuid[]);

create or replace function public.search_products_hybrid(
  query_embedding vector(1536),
  query_text      text,
  k               int     default 24,
  filter_gender   text    default null,
  filter_types    text[]  default null,
  exclude_ids     uuid[]  default '{}'::uuid[]
)
returns table(
  id                uuid,
  product_id        uuid,
  video_url         text,
  thumbnail_url     text,
  affiliate_url     text,
  duration_seconds  numeric,
  is_elite          boolean,
  product_name      text,
  product_brand     text,
  product_price     text,
  product_image_url text,
  product_url       text,
  product_gender    text,
  product_type      text,
  concept_doc       text,
  concept_facets    jsonb,
  rrf_score         double precision,
  dense_rank        bigint,
  bm25_rank         bigint
)
language sql
stable
as $$
  with candidates as (
    select p.id
    from public.products p
    where p.is_active = true
      and (filter_gender is null or p.gender is null or p.gender = filter_gender or p.gender = 'unisex')
      and (
        filter_types is null
        or array_length(filter_types, 1) is null
        or (p.type is not null and p.type = any(filter_types))
      )
      and (exclude_ids is null or array_length(exclude_ids, 1) is null or p.id <> all(exclude_ids))
  ),
  dense as (
    select
      c.id,
      row_number() over (order by p.text_embedding <=> query_embedding) as rk
    from candidates c
    join public.products p on p.id = c.id
    where p.text_embedding is not null
    order by p.text_embedding <=> query_embedding
    limit k * 4
  ),
  bm25 as (
    select
      c.id,
      row_number() over (
        order by ts_rank_cd(
          setweight(to_tsvector('english', coalesce(p.name,         '')), 'A') ||
          setweight(to_tsvector('english', coalesce(p.brand,        '')), 'B') ||
          setweight(to_tsvector('english', coalesce(p.type,         '')), 'B') ||
          setweight(to_tsvector('english', coalesce(p.description,  '')), 'C') ||
          setweight(to_tsvector('english', coalesce(p.concept_doc,  '')), 'B') ||
          setweight(to_tsvector('english', coalesce(p.facet_text,   '')), 'C'),
          websearch_to_tsquery('english', query_text)
        ) desc
      ) as rk
    from candidates c
    join public.products p on p.id = c.id
    where coalesce(btrim(query_text), '') <> ''
      and (
        setweight(to_tsvector('english', coalesce(p.name,         '')), 'A') ||
        setweight(to_tsvector('english', coalesce(p.brand,        '')), 'B') ||
        setweight(to_tsvector('english', coalesce(p.type,         '')), 'B') ||
        setweight(to_tsvector('english', coalesce(p.description,  '')), 'C') ||
        setweight(to_tsvector('english', coalesce(p.concept_doc,  '')), 'B') ||
        setweight(to_tsvector('english', coalesce(p.facet_text,   '')), 'C')
      ) @@ websearch_to_tsquery('english', query_text)
    limit k * 4
  ),
  fused as (
    select
      coalesce(d.id, b.id) as id,
      (coalesce(1.0 / (60.0 + d.rk), 0.0) +
       coalesce(1.0 / (60.0 + b.rk), 0.0))::double precision as rrf_score,
      d.rk as dense_rank,
      b.rk as bm25_rank
    from dense d
    full outer join bm25 b on d.id = b.id
    order by rrf_score desc
    limit k
  )
  select
    p.id,
    p.id           as product_id,
    null::text     as video_url,
    null::text     as thumbnail_url,
    null::text     as affiliate_url,
    null::numeric  as duration_seconds,
    p.is_elite,
    p.name         as product_name,
    p.brand        as product_brand,
    p.price        as product_price,
    p.image_url    as product_image_url,
    p.url          as product_url,
    p.gender       as product_gender,
    p.type         as product_type,
    p.concept_doc,
    p.concept_facets,
    f.rrf_score,
    f.dense_rank,
    f.bm25_rank
  from fused f
  join public.products p on p.id = f.id
  order by f.rrf_score desc;
$$;

-- search_creatives_hybrid: same body as 067, +facet_text at BM25 weight C.

drop function if exists public.search_creatives_hybrid(vector, text, int, text, text[], boolean, uuid[], int, int);

create or replace function public.search_creatives_hybrid(
  query_embedding   vector(1536),
  query_text        text,
  k                 int     default 24,
  filter_gender     text    default null,
  filter_types      text[]  default null,
  require_elite     boolean default false,
  exclude_ids       uuid[]  default '{}'::uuid[],
  min_results       int     default 8,
  max_per_product   int     default 2
)
returns table(
  id                uuid,
  product_id        uuid,
  video_url         text,
  thumbnail_url     text,
  affiliate_url     text,
  duration_seconds  numeric,
  is_elite          boolean,
  product_name      text,
  product_brand     text,
  product_price     text,
  product_image_url text,
  product_url       text,
  product_gender    text,
  product_type      text,
  concept_doc       text,
  concept_facets    jsonb,
  rrf_score         double precision,
  dense_rank        bigint,
  bm25_rank         bigint,
  type_match        boolean
)
language plpgsql
stable
as $$
declare
  v_strict_count int;
  v_use_types text[] := filter_types;
begin
  if filter_types is not null and array_length(filter_types, 1) is not null then
    select count(*) into v_strict_count
    from public.product_creative pc
    join public.products p on p.id = pc.product_id
    where pc.status = 'live'
      and pc.enabled = true
      and pc.video_url is not null
      and p.is_active = true
      and (filter_gender is null or p.gender is null or p.gender = filter_gender or p.gender = 'unisex')
      and p.type = any(filter_types);

    if v_strict_count < min_results then
      v_use_types := null;
    end if;
  end if;

  return query
  with candidates as (
    select pc.id, pc.product_id,
           (filter_types is not null
            and array_length(filter_types, 1) is not null
            and p.type = any(filter_types)) as type_match
    from public.product_creative pc
    join public.products p on p.id = pc.product_id
    where pc.status = 'live'
      and pc.enabled = true
      and pc.video_url is not null
      and p.is_active = true
      and (not require_elite or pc.is_elite = true)
      and (filter_gender is null or p.gender is null or p.gender = filter_gender or p.gender = 'unisex')
      and (
        v_use_types is null
        or array_length(v_use_types, 1) is null
        or (p.type is not null and p.type = any(v_use_types))
      )
      and (exclude_ids is null or array_length(exclude_ids, 1) is null or pc.id <> all(exclude_ids))
  ),
  dense as (
    select
      c.id,
      row_number() over (order by pc.text_embedding <=> query_embedding) as rk
    from candidates c
    join public.product_creative pc on pc.id = c.id
    where pc.text_embedding is not null
    order by pc.text_embedding <=> query_embedding
    limit k * 6
  ),
  bm25 as (
    select
      c.id,
      row_number() over (
        order by ts_rank_cd(
          setweight(to_tsvector('english', coalesce(p.name,           '')), 'A') ||
          setweight(to_tsvector('english', coalesce(p.brand,          '')), 'B') ||
          setweight(to_tsvector('english', coalesce(p.type,           '')), 'B') ||
          setweight(to_tsvector('english', coalesce(p.description,    '')), 'C') ||
          setweight(to_tsvector('english', coalesce(pc.concept_doc,   '')), 'B') ||
          setweight(to_tsvector('english', coalesce(pc.facet_text,    '')), 'C') ||
          setweight(to_tsvector('english', coalesce(p.facet_text,     '')), 'C'),
          websearch_to_tsquery('english', query_text)
        ) desc
      ) as rk
    from candidates c
    join public.product_creative pc on pc.id = c.id
    join public.products p          on p.id  = c.product_id
    where coalesce(btrim(query_text), '') <> ''
      and (
        setweight(to_tsvector('english', coalesce(p.name,           '')), 'A') ||
        setweight(to_tsvector('english', coalesce(p.brand,          '')), 'B') ||
        setweight(to_tsvector('english', coalesce(p.type,           '')), 'B') ||
        setweight(to_tsvector('english', coalesce(p.description,    '')), 'C') ||
        setweight(to_tsvector('english', coalesce(pc.concept_doc,   '')), 'B') ||
        setweight(to_tsvector('english', coalesce(pc.facet_text,    '')), 'C') ||
        setweight(to_tsvector('english', coalesce(p.facet_text,     '')), 'C')
      ) @@ websearch_to_tsquery('english', query_text)
    limit k * 6
  ),
  fused as (
    select
      coalesce(d.id, b.id) as id,
      (coalesce(1.0 / (60.0 + d.rk), 0.0) +
       coalesce(1.0 / (60.0 + b.rk), 0.0))::double precision as rrf_score,
      d.rk as dense_rank,
      b.rk as bm25_rank
    from dense d
    full outer join bm25 b on d.id = b.id
  ),
  ranked as (
    select
      f.id, f.rrf_score, f.dense_rank, f.bm25_rank,
      pc.product_id,
      c.type_match,
      row_number() over (
        partition by pc.product_id
        order by (case when c.type_match then 1 else 0 end) desc, f.rrf_score desc
      ) as per_product_rank
    from fused f
    join public.product_creative pc on pc.id = f.id
    join candidates c on c.id = f.id
  ),
  diversified as (
    select * from ranked
    where ranked.per_product_rank <= greatest(max_per_product, 1)
    order by
      (case when ranked.type_match then 0 else 1 end),
      ranked.rrf_score desc
    limit k
  )
  select
    pc.id,
    pc.product_id,
    pc.video_url,
    pc.thumbnail_url,
    pc.affiliate_url,
    pc.duration_seconds,
    pc.is_elite,
    p.name        as product_name,
    p.brand       as product_brand,
    p.price       as product_price,
    p.image_url   as product_image_url,
    p.url         as product_url,
    p.gender      as product_gender,
    p.type        as product_type,
    pc.concept_doc,
    pc.concept_facets,
    di.rrf_score,
    di.dense_rank,
    di.bm25_rank,
    di.type_match
  from diversified di
  join public.product_creative pc on pc.id = di.id
  join public.products p          on p.id  = pc.product_id
  order by
    (case when di.type_match then 0 else 1 end),
    di.rrf_score desc;
end;
$$;
